# Base controller parameters
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
base_global_planner: "navfn/NavfnROS"

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.4
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  holonomic_robot: false

NavfnROS:
  allow_unknown: true
  tolerance: 0.1

# Costmap parameters
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: false
  
# Sensor parameters
scan:
  topic: /scan
  max_range: 10.0
  min_angle: -1.57
  max_angle: 1.57

# Recovery behavior parameters
recovery_behaviors:
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: clear_costmap_recovery
    type: clear_costmap_recovery/ClearCostmapRecovery